# QKD 파라미터 설정 파일

# Detection parameters
detection:
  eta_d: 0.06779257921161397              # detection efficiency of single-photon detector (%)
  Y_0: 2.32739222806287e-07                  # dark count rate
  e_d: 0.04339073000818308                    # misalignment rate

# Fiber parameters
fiber:
  alpha: 0.21581100947678922                  # attenuation coefficient of single-mode fiber

# Error correction parameters
error_correction:
  zeta: 1.2337498258560773                   # efficiency of error correction
  e_0: 0.4199949831636006                      # error rate of the background (ref 23)

# Security parameters
security:
  eps_sec: 6.870614282613291e-11               # security parameter
  eps_cor: 1.005198118065676e-16                # correctness parameter

# System parameters
system:
  N: 1930783753.6547112                      # number of optical pulses sent by Alice
  Lambda: null                    # probability of bit value 1 observed in Xk

# Reference data for comparison
reference:
        # L =    0,      10,     20,     30,     40,     50,     60,     70,     80,     90,    100,    110
  skr_values: [3.0e-3, 1.7e-3, 9.0e-4, 5.0e-4, 2.9e-4, 1.7e-4, 8.0e-5, 4.0e-5, 1.9e-5, 8.0e-6, 3.0e-6, 3.0e-7]
  optimized : [0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 0.0e-9, 9.883606e-06, 0.0e-9]
